[package]
name = "rust-http-v0"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
cargo-watch = "8.5.3"
hyper = "1.6.0"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.46.1"
